# Permalinks
permalink: pretty

# Setup
host: localhost
title: Supreeth Prajwal Shashikumar
url: https://supreethprajwal.github.io

author:
    name: Supreeth Prajwal Shashikumar
    url: https://twitter.com/sprajw
    email: supreeth@gatech.edu

future: true
permalink: "/:title/"

pages_list:
    Research: '/research'
    Teaching: '/teaching'
    Publications: '/publications'

markdown: kramdown

gems:
    - jekyll-seo-tag
